{
  "language": "java",
  "sudo": false,
  "jdk": [
    "openjdk11"
  ],
  "script": [
    "cd .\demo\",
    "mvn clean package",
    "mvn test package"
  ],
  "after_success": [
    "bash <(curl -s https://codecov.io/bash)"
  ]
}
